[workspace]
resolver = "2"
members = ["orbit-cli", "orbit-client", "orbit-core", "orbit-server"]

[workspace.package]
license = "MIT"
edition = "2021"
authors = ["Miguel Piedrafita <rust@miguel.build>"]
