FROM --platform=linux/amd64 clux/muslrust AS builder
WORKDIR /orbit-cli
COPY . .
RUN cargo build --release --bin orbit-cli

FROM --platform=linux/amd64 alpine AS runtime
WORKDIR /orbit-cli
COPY --from=builder /orbit-cli/target/x86_64-unknown-linux-musl/release/orbit-cli /usr/local/bin/orbit

ENTRYPOINT ["/usr/local/bin/orbit"]
