FROM --platform=linux/amd64 clux/muslrust AS builder
WORKDIR /orbit
COPY . .
RUN cargo build --release --bin orbit-server

FROM --platform=linux/amd64 alpine AS runtime
WORKDIR /orbit
COPY --from=builder /orbit/target/x86_64-unknown-linux-musl/release/orbit-server /usr/local/bin

EXPOSE 8000
ENTRYPOINT ["/usr/local/bin/orbit-server"]

HEALTHCHECK --interval=5m \
    CMD curl -f http://localhost:8000/ || exit 1
