name: Release

on:
    release:
        types: [published]

permissions:
    contents: write
    packages: write

jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - image: orbit-server
                      dockerfile: ./Dockerfile.server
                    - image: orbit-cli
                      dockerfile: ./Dockerfile.cli
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/m1guelpf/${{ matrix.image }}
                  tags: |
                      type=semver,pattern={{major}}
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: '${{ github.actor }}'
                  password: '${{ secrets.GITHUB_TOKEN }}'

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: .
                  cache-from: type=gha
                  cache-to: 'type=gha,mode=max'
                  file: '${{ matrix.dockerfile }}'
                  tags: '${{ steps.meta.outputs.tags }}'
                  labels: '${{ steps.meta.outputs.labels }}'
              env:
                  DOCKER_BUILD_SUMMARY: false
                  DOCKER_BUILD_RECORD_UPLOAD: false

    binaries:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  target: x86_64-unknown-linux-musl

            - name: Build
              run: cargo build --release --bins

            - name: Upload orbit-server binary
              uses: shogo82148/actions-upload-release-asset@v1
              with:
                  asset_path: target/release/orbit-server
                  upload_url: ${{ github.event.release.upload_url }}

            - name: Upload orbit-cli binary
              uses: shogo82148/actions-upload-release-asset@v1
              with:
                  asset_path: target/release/orbit-cli
                  upload_url: ${{ github.event.release.upload_url }}
